apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: llm-gateway
spec:
  gatewayClassName: example-gateway-class
  listeners:
  - name: http
    protocol: HTTP
    port: 8080
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: llm-route
spec:
  parentRefs:
    - name: llm-gateway
  hostnames:
    - "www.example.com"
  rules:
    - backendRefs:
        - name: llm-pool
          kind: InferencePool
          group: inference.networking.x-k8s.io
          port: 8080
          weight: 1
---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: llm-pool
spec:
  extensionRef:
    failureMode: FailClose
    group: ""
    kind: Service
    name: llm-pool-endpoint-picker
    portNumber: 9002
  selector:
    app: llm
  targetPortNumber: 8080
