// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// EndpointPickerExtensionApplyConfiguration represents a declarative configuration of the EndpointPickerExtension type for use
// with apply.
type EndpointPickerExtensionApplyConfiguration struct {
	PoolRef *InferencePoolObjRefApplyConfiguration `json:"poolRef,omitempty"`
}

// EndpointPickerExtensionApplyConfiguration constructs a declarative configuration of the EndpointPickerExtension type for use with
// apply.
func EndpointPickerExtension() *EndpointPickerExtensionApplyConfiguration {
	return &EndpointPickerExtensionApplyConfiguration{}
}

// WithPoolRef sets the PoolRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PoolRef field is set to the value of the last call.
func (b *EndpointPickerExtensionApplyConfiguration) WithPoolRef(value *InferencePoolObjRefApplyConfiguration) *EndpointPickerExtensionApplyConfiguration {
	b.PoolRef = value
	return b
}
