// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// InferenceExtensionApplyConfiguration represents a declarative configuration of the InferenceExtension type for use
// with apply.
type InferenceExtensionApplyConfiguration struct {
	EndpointPickers []EndpointPickerExtensionApplyConfiguration `json:"endpointPickers,omitempty"`
}

// InferenceExtensionApplyConfiguration constructs a declarative configuration of the InferenceExtension type for use with
// apply.
func InferenceExtension() *InferenceExtensionApplyConfiguration {
	return &InferenceExtensionApplyConfiguration{}
}

// WithEndpointPickers adds the given value to the EndpointPickers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EndpointPickers field.
func (b *InferenceExtensionApplyConfiguration) WithEndpointPickers(values ...*EndpointPickerExtensionApplyConfiguration) *InferenceExtensionApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEndpointPickers")
		}
		b.EndpointPickers = append(b.EndpointPickers, *values[i])
	}
	return b
}
