// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// InferencePoolObjRefApplyConfiguration represents a declarative configuration of the InferencePoolObjRef type for use
// with apply.
type InferencePoolObjRefApplyConfiguration struct {
	Group *string `json:"group,omitempty"`
	Kind  *string `json:"kind,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// InferencePoolObjRefApplyConfiguration constructs a declarative configuration of the InferencePoolObjRef type for use with
// apply.
func InferencePoolObjRef() *InferencePoolObjRefApplyConfiguration {
	return &InferencePoolObjRefApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *InferencePoolObjRefApplyConfiguration) WithGroup(value string) *InferencePoolObjRefApplyConfiguration {
	b.Group = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *InferencePoolObjRefApplyConfiguration) WithKind(value string) *InferencePoolObjRefApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *InferencePoolObjRefApplyConfiguration) WithName(value string) *InferencePoolObjRefApplyConfiguration {
	b.Name = &value
	return b
}
